# Application Configuration
# Generated: 2025-10-13T18:00:00Z

application:
  name: 'DateExtractor'
  version: '1.0.0'
  launchedAt: '2025-10-13T08:00:00Z'

database:
  host: 'localhost'
  port: 5432
  created: '2023-01-15T09:30:00Z'
  lastBackup: '2025-10-12T23:00:00Z'
  nextBackup: '2025-10-13T23:00:00Z'
  retentionPeriod: 90 # days

api:
  endpoint: 'https://api.example.com'
  timeout: 30000 # milliseconds
  rateLimitReset: '2025-10-13T12:00:00Z'

security:
  certificateExpiry: '2025-12-31T23:59:59Z'
  certificateIssued: '2024-01-01T00:00:00Z'
  lastSecurityScan: '2025-10-10T10:00:00Z'
  nextSecurityScan: '2025-10-17T10:00:00Z'

maintenance:
  lastMaintenance: '2025-10-01T02:00:00Z'
  nextMaintenance: '2025-11-01T02:00:00Z'
  maintenanceWindow:
    start: '2025-10-14T02:00:00Z'
    end: '2025-10-14T04:00:00Z'

monitoring:
  enabled: true
  reportingInterval: 300 # seconds
  alertsEnabled: true
  lastAlert: '2025-10-13T10:30:00Z'

backups:
  - id: 'backup-001'
    created: '2025-10-12T23:00:00Z'
    size: '2.5GB'
    status: 'completed'
  - id: 'backup-002'
    created: '2025-10-11T23:00:00Z'
    size: '2.4GB'
    status: 'completed'
  - id: 'backup-003'
    created: '2025-10-10T23:00:00Z'
    size: '2.3GB'
    status: 'completed'

events:
  - eventId: 'E-001'
    eventName: 'System Upgrade'
    scheduledDate: '2025-10-20T00:00:00Z'
    estimatedDuration: 120 # minutes
  - eventId: 'E-002'
    eventName: 'Database Migration'
    scheduledDate: '2025-11-01T02:00:00Z'
    estimatedDuration: 180 # minutes
  - eventId: 'E-003'
    eventName: 'Security Patch'
    scheduledDate: '2025-10-15T03:00:00Z'
    estimatedDuration: 60 # minutes

logs:
  retention:
    debugLogs: 7 # days
    infoLogs: 30 # days
    errorLogs: 90 # days
  lastRotation: '2025-10-13T00:00:00Z'
  nextRotation: '2025-10-14T00:00:00Z'
  archiveOlderThan: '2025-09-13T00:00:00Z'

users:
  - username: 'admin'
    lastLogin: '2025-10-13T08:00:00Z'
    accountCreated: '2023-01-01T00:00:00Z'
    passwordExpires: '2025-12-31T23:59:59Z'
  - username: 'operator'
    lastLogin: '2025-10-12T14:30:00Z'
    accountCreated: '2023-06-15T09:00:00Z'
    passwordExpires: '2025-11-30T23:59:59Z'
  - username: 'developer'
    lastLogin: '2025-10-13T09:45:00Z'
    accountCreated: '2024-03-20T10:00:00Z'
    passwordExpires: '2025-10-31T23:59:59Z'

metadata:
  configVersion: '3.2.1'
  createdAt: '2025-10-13T18:00:00.000Z'
  updatedAt: '2025-10-13T18:00:00.000Z'
  validUntil: '2025-10-14T18:00:00.000Z'
